"""The gateway's MCP surface. This file is a wire format, not a design.

Everything it does is: read the generated manifest, publish one tool per agent,
and forward a call to dispatch.call_tool. No policy, no caching, no cleverness.
The gateway is the only process that holds the Docker socket; the agent
containers it starts never do, which is what stops an agent starting a sibling.
"""

from __future__ import annotations

import os
from typing import Any

from mcp.server.mcpserver import MCPServer

from .dispatch import DEFAULT_MANIFEST, GatewayError, call_tool, load_manifest, tool_defs

#: Read once at startup. The manifest is regenerated by scripts/compile.sh and
#: the gateway is restarted when agents change, so there is nothing to reload.
MANIFEST = load_manifest(os.environ.get("CLOAKAI_MANIFEST", DEFAULT_MANIFEST))

# mcp 2.x renamed FastMCP to MCPServer; the v1 name raises on import.
mcp = MCPServer("cloakai")


def _expose(name: str, description: str) -> None:
    """Publish one agent as a tool.

    The tool takes a single string and returns the agent's output as text. The
    docstring is deliberately absent: the tool's advertised description comes
    from the agent's own agent.json, because that text is what a client model
    reads when it decides which agent to call.
    """

    @mcp.tool(name=name, description=description)
    def call(prompt: str) -> str:
        try:
            return call_tool(MANIFEST, name, {"prompt": prompt})
        except GatewayError as exc:
            return f"error: {exc}"


for _tool in tool_defs(MANIFEST):
    _expose(_tool["name"], _tool["description"])


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
